version: "3.8"

services:
  db:
    image: postgres:15
    container_name: royal_docs.db
    environment:
      POSTGRES_USER: ${POSTGRES_USERNAME}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
    volumes:
      - db_data:/var/lib/postgresql/data
    ports:
      - "${POSTGRES_PORT}:5432"
    networks:
      - global_net
    restart: unless-stopped
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U ${POSTGRES_USERNAME} -d ${POSTGRES_DB}"]
      interval: 2s
      timeout: 5s
      retries: 15

  init_container:
    build:
      context: .
    container_name: royal_docs.init_container
    command: alembic upgrade head
    environment:
      POSTGRES_HOST: ${POSTGRES_HOST}
      POSTGRES_PORT: 5432
      POSTGRES_DB: ${POSTGRES_DB}
      POSTGRES_USERNAME: ${POSTGRES_USERNAME}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}

      UVICORN_HOST: ${UVICORN_HOST}
      UVICORN_PORT: ${UVICORN_PORT}
      UVICORN_LOG_LEVEL: ${UVICORN_LOG_LEVEL}
      UVICORN_WORKERS: ${UVICORN_WORKERS}
      UVICORN_LIMIT_CONCURRENCY: ${UVICORN_LIMIT_CONCURRENCY}

      HOST_ID: ${HOST_ID}
      INSTANCE_ID: ${INSTANCE_ID}

      SECRET_KEY: ${SECRET_KEY}
    depends_on:
      db:
        condition: service_healthy
    networks:
      - global_net
    restart: "no"

  royal_docs_api:
    build:
      context: .
    container_name: royal_docs.api
    environment:
      POSTGRES_HOST: ${POSTGRES_HOST}
      POSTGRES_PORT: 5432
      POSTGRES_DB: ${POSTGRES_DB}
      POSTGRES_USERNAME: ${POSTGRES_USERNAME}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}

      UVICORN_HOST: ${UVICORN_HOST}
      UVICORN_PORT: ${UVICORN_PORT}
      UVICORN_LOG_LEVEL: ${UVICORN_LOG_LEVEL}
      UVICORN_WORKERS: ${UVICORN_WORKERS}
      UVICORN_LIMIT_CONCURRENCY: ${UVICORN_LIMIT_CONCURRENCY}

      HOST_ID: ${HOST_ID}
      INSTANCE_ID: ${INSTANCE_ID}

      SECRET_KEY: ${SECRET_KEY}
    ports:
      - ${UVICORN_PORT}:${UVICORN_PORT}
    depends_on:
      init_container:
        condition: service_completed_successfully
    networks:
      - global_net
    restart: unless-stopped

volumes:
  db_data:

networks:
  global_net:
    driver: bridge